# Generated by Django 2.0.6 on 2018-06-17 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GL_username', models.CharField(default='', max_length=50)),
                ('GL_address', models.CharField(default='', max_length=100)),
                ('GL_sex', models.CharField(choices=[('unknown', 'unknown'), ('m', 'male'), ('f', 'female')], default='unknown', max_length=20)),
                ('GL_birthday', models.DateField(default='', max_length=20)),
                ('GL_email', models.EmailField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=100)),
                ('GL_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vips.GlUser')),
            ],
        ),
        migrations.CreateModel(
            name='Vip1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_level_number', models.CharField(default='1', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vips.GlUser')),
            ],
        ),
        migrations.CreateModel(
            name='Vip2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_level_number', models.CharField(default='2', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vips.GlUser')),
                ('higher_vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vips.Vip1')),
            ],
        ),
        migrations.CreateModel(
            name='Vip3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_level_number', models.CharField(default='3', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vips.GlUser')),
                ('higher_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vips.Vip2')),
            ],
        ),
        migrations.CreateModel(
            name='Vip4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_level_number', models.CharField(default='4', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vips.GlUser')),
                ('higher_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vips.Vip3')),
                ('total_amount', models.ManyToManyField(blank=True, to='vips.Selling')),
            ],
        ),
        migrations.CreateModel(
            name='VipGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_group', models.ManyToManyField(to='vips.GlUser')),
            ],
        ),
        migrations.AddField(
            model_name='vip3',
            name='lower_vip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vips.VipGroup'),
        ),
        migrations.AddField(
            model_name='vip3',
            name='total_amount',
            field=models.ManyToManyField(blank=True, to='vips.Selling'),
        ),
        migrations.AddField(
            model_name='vip2',
            name='lower_vip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vips.VipGroup'),
        ),
        migrations.AddField(
            model_name='vip2',
            name='total_amount',
            field=models.ManyToManyField(blank=True, to='vips.Selling'),
        ),
        migrations.AddField(
            model_name='vip1',
            name='lower_vip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vips.VipGroup'),
        ),
        migrations.AddField(
            model_name='vip1',
            name='total_amount',
            field=models.ManyToManyField(blank=True, to='vips.Selling'),
        ),
    ]
